language: python
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy3
  - TOXENV=cover
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install -r requirements-dev.txt"
  - "pip install coveralls"
script:
  - make test
after_success:
  - '[ "$TOXENV" == "cover" ] && coveralls'
